#!/usr/bin/env php
<?php
require __DIR__.'/../vendor/autoload.php';

use Symfony\Component\Console\Application;

$application = new Application('echo', '1.0.0');
$loadCurrencyCommand = new \Struct\Development\Command\LoadCurrencyCommand();

$application->add($loadCurrencyCommand);
$application->run();