#!/usr/bin/env php
<?php
require __DIR__.'/../vendor/autoload.php';

use Struct\Development\Command\LoadCurrencyCommand;
use Symfony\Component\Console\Application;

$application = new Application('echo', '1.0.0');
$loadCurrencyCommand = new LoadCurrencyCommand();

$application->add($loadCurrencyCommand);
$application->run();
